### ISSUE TITLE
Fix course mode currency errors

### ISSUE THREAD

**Issue by renevatium** [proversity-org/edx-platform#141]
```
 Internal Server Error: /courses/course-v1:edX+DemoX+Demo_Course/about
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/util/cache.py", line 85, in wrapper
    return view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/views/views.py", line 598, in course_about
    settings.PAID_COURSE_REGISTRATION_CURRENCY[0]
  File "/edx/app/edxapp/edx-platform/common/djangoapps/course_modes/models.py", line 626, in min_course_price_for_currency
    return min(mode.min_price for mode in modes if mode.currency.lower() == currency.lower())
ValueError: min() arg is an empty sequence
```

**Comment by renevatium** [comment]
This occurs when a course has no mode. Default to "fake" audit mode as fix
